# Generated by Django 4.0 on 2021-12-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ManyToManyField(to='users.Parent'),
        ),
    ]
