# Generated by Django 4.0 on 2021-12-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_student_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent',
        ),
        migrations.AddField(
            model_name='parent',
            name='student',
            field=models.ManyToManyField(to='users.Student'),
        ),
    ]
