# Generated by Django 4.0 on 2021-12-29 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_student_parent_parent_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='vocational_class',
        ),
        migrations.RemoveField(
            model_name='student',
            name='vocational_level',
        ),
        migrations.DeleteModel(
            name='VocationalClass',
        ),
        migrations.DeleteModel(
            name='VocationalLevel',
        ),
    ]
