# Generated by Django 4.0 on 2022-01-07 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_remove_instructor_school_remove_schooladmin_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ManyToManyField(related_name='Children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
