# Generated by Django 4.0 on 2022-01-10 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_student_parent_delete_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooladmin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vocationalcoordinator',
            name='user',
        ),
        migrations.AlterField(
            model_name='school',
            name='abbreviation',
            field=models.CharField(default=' ', help_text=' Enter the abbreviation for this school', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='Children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='SchoolAdmin',
        ),
        migrations.DeleteModel(
            name='VocationalCoordinator',
        ),
    ]
