# Generated by Django 4.0 on 2022-01-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_profile_school_alter_student_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('f', 'Female'), ('m', 'Male')], default='f', max_length=1),
        ),
    ]
