# Generated by Django 4.0 on 2022-01-31 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_student_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('user__last_name', 'user__first_name')},
        ),
    ]
