# Generated by Django 4.0 on 2022-06-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_student_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='active',
        ),
    ]
