# Generated by Django 4.0 on 2022-12-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_school_email_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
