# Generated by Django 4.0 on 2022-12-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_school_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='email_password',
            field=models.CharField(default='', max_length=254),
        ),
    ]
