# Generated by Django 4.0 on 2022-12-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_school_email_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='abbreviation',
            field=models.CharField(default=' ', help_text=' Enter the abbreviation for this school', max_length=6, unique=True),
        ),
    ]
