# Generated by Django 4.0 on 2023-08-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_profile_updated_at_student_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='email_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
