# Generated by Django 4.0 on 2021-12-29 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_remove_student_vocational_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocationalClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VocationalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VocationalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('vocational_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocational.vocationalclass')),
                ('vocational_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocational.vocationallevel')),
            ],
        ),
    ]
