# Generated by Django 4.0 on 2022-01-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocationallevel',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
