# Generated by Django 4.0 on 2022-01-21 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_student_gender'),
        ('vocational', '0003_alter_vocationalclass_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocationalstatus',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
