# Generated by Django 4.0 on 2022-01-21 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0005_vocationalindicator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vocationalindicator',
            unique_together={('number', 'level')},
        ),
    ]
