# Generated by Django 4.0 on 2022-01-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0006_alter_vocationalindicator_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocationalindicator',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
