# Generated by Django 4.0 on 2022-01-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0007_alter_vocationalindicator_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vocationalindicator',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='vocationalindicator',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='vocationalindicator',
            unique_together={('name', 'level')},
        ),
    ]
