# Generated by Django 4.0 on 2022-01-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0010_schoolyear_quarter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('school', '-is_active', 'name')},
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
