# Generated by Django 4.0 on 2022-01-28 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0014_student_gender'),
        ('vocational', '0012_alter_vocationalindicator_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vocational.department')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocational.quarter')),
                ('student', models.ManyToManyField(blank=True, related_name='student_assignment', to='users.Student')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vocational.department')),
                ('instructor', models.ManyToManyField(blank=True, related_name='instructor_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
