# Generated by Django 4.0 on 2022-01-31 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0016_alter_student_graduation_year'),
        ('vocational', '0014_alter_studentassignment_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EthicsGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('F', 'Formative'), ('S', 'Summative')], default='F', max_length=1)),
                ('commendation', models.CharField(max_length=300)),
                ('recommendation', models.CharField(max_length=300)),
                ('comment', models.CharField(max_length=300)),
                ('student_discussed', models.DateField()),
                ('date_submitted', models.DateField()),
                ('vc_validated', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vocational.department')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vocational.vocationallevel')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vocational.quarter')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=3)),
                ('comment', models.CharField(max_length=300)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vocational.ethicsgrade')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vocational.vocationalindicator')),
            ],
        ),
        migrations.CreateModel(
            name='GradeMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('read', models.BooleanField(default='False')),
                ('date', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocational.ethicsgrade')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user')),
            ],
        ),
    ]
