# Generated by Django 4.0 on 2022-01-31 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0015_ethicsgrade_indicatorgrade_grademessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethicsgrade',
            name='date_submitted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ethicsgrade',
            name='student_discussed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ethicsgrade',
            name='vc_validated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorgrade',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
