# Generated by Django 4.0 on 2022-05-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0017_commentformativegrade_indicatorformativegrade_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VocationalLevel',
            new_name='EthicsLevel',
        ),
        migrations.AlterField(
            model_name='commentformativegrade',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
