# Generated by Django 4.0 on 2022-05-23 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0018_rename_vocationallevel_ethicslevel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VocationalIndicator',
            new_name='EthicsIndicator',
        ),
    ]
