# Generated by Django 4.0 on 2022-05-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0019_rename_vocationalindicator_ethicsindicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorsummativegrade',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
