# Generated by Django 4.0 on 2022-05-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0020_alter_indicatorsummativegrade_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ethicsgrade',
            name='date_submitted',
        ),
        migrations.AddField(
            model_name='ethicsgrade',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ethicsgrade',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
