# Generated by Django 4.0 on 2022-05-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0021_remove_ethicsgrade_date_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethicsgrade',
            name='commendation',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ethicsgrade',
            name='recommendation',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='indicatorformativegrade',
            unique_together={('indicator', 'grade')},
        ),
        migrations.AlterUniqueTogether(
            name='indicatorsummativegrade',
            unique_together={('indicator', 'grade')},
        ),
        migrations.DeleteModel(
            name='CommentFormativeGrade',
        ),
    ]
