# Generated by Django 4.0 on 2022-06-15 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0024_alter_indicatorsummativegrade_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VocationalAssignment',
        ),
    ]
