# Generated by Django 4.0 on 2022-06-16 08:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0016_alter_student_graduation_year'),
        ('vocational', '0025_delete_vocationalassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('value',),
            },
        ),
        migrations.CreateModel(
            name='SkillGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_discussed', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('commendation', models.CharField(blank=True, max_length=300, null=True)),
                ('recommendation', models.CharField(blank=True, max_length=300, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vocational.department')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vocational.ethicslevel')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vocational.quarter')),
                ('skill_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vocational.skillvalue')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
