# Generated by Django 4.0 on 2022-06-16 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0026_skillvalue_skillgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillvalue',
            name='number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skillvalue',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1.5)]),
        ),
    ]
