# Generated by Django 4.0 on 2022-06-16 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vocational', '0028_vocationalskill_weight_alter_vocationalskill_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentassignment',
            name='student',
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='student_assignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
