# Generated by Django 4.0 on 2022-06-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_student_active'),
        ('vocational', '0029_remove_studentassignment_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentassignment',
            name='user',
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='student_assignment', to='users.Student'),
        ),
    ]
