# Generated by Django 4.0 on 2022-06-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0030_remove_studentassignment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
