# Generated by Django 4.0 on 2022-06-17 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0033_remove_studentassignment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillgrade',
            name='skill_value',
        ),
        migrations.AddField(
            model_name='skillvalue',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vocational.skillgrade'),
        ),
    ]
