# Generated by Django 4.0 on 2022-06-17 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0034_remove_skillgrade_skill_value_skillvalue_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillvalue',
            name='grade',
        ),
        migrations.CreateModel(
            name='IndicatorSkillGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocational.ethicsgrade')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vocational.skillvalue')),
            ],
            options={
                'unique_together': {('indicator', 'grade')},
            },
        ),
    ]
