# Generated by Django 4.0 on 2022-06-17 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0036_alter_indicatorskillgrade_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorskillgrade',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocational.skillgrade'),
        ),
    ]
