# Generated by Django 4.0 on 2022-07-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0018_remove_student_active'),
        ('vocational', '0037_alter_indicatorskillgrade_grade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EthicsIndicator',
            new_name='EthicsDefinition',
        ),
        migrations.RenameModel(
            old_name='EthicsGrade',
            new_name='EthicsGradeRecord',
        ),
    ]
