# Generated by Django 4.0 on 2022-07-20 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0039_rename_indicatorformativegrade_ethicsformativegrade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ethicsformativegrade',
            old_name='value',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='ethicssummativegrade',
            old_name='value',
            new_name='score',
        ),
    ]
