# Generated by Django 4.0 on 2022-07-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0040_rename_value_ethicsformativegrade_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethicsgraderecord',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
