# Generated by Django 4.0 on 2022-07-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0041_alter_ethicsgraderecord_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethicsgraderecord',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
