# Generated by Django 4.0 on 2022-07-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0042_ethicsgraderecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethicsgraderecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
