# Generated by Django 4.0 on 2022-07-21 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0043_alter_ethicsgraderecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethicsgraderecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
