# Generated by Django 4.0 on 2022-07-21 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_student_active'),
        ('vocational', '0045_rename_date_ethicsgraderecord_evaluation_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ethicsgraderecord',
            unique_together={('student', 'department', 'evaluation_date')},
        ),
    ]
