# Generated by Django 4.0 on 2022-07-27 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0047_alter_ethicsformativegrade_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ethicssummativegrade',
            old_name='indicator',
            new_name='ethic',
        ),
        migrations.AlterUniqueTogether(
            name='ethicsformativegrade',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ethicssummativegrade',
            unique_together=set(),
        ),
    ]
