# Generated by Django 4.0 on 2022-07-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0048_rename_indicator_ethicssummativegrade_ethic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ethicsformativegrade',
            old_name='indicator',
            new_name='ethic',
        ),
    ]
