# Generated by Django 4.0 on 2022-07-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0049_rename_indicator_ethicsformativegrade_ethic'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ethicsformativegrade',
            unique_together={('ethic', 'grade')},
        ),
        migrations.AlterUniqueTogether(
            name='ethicssummativegrade',
            unique_together={('ethic', 'grade')},
        ),
    ]
