# Generated by Django 4.0 on 2022-07-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0050_alter_ethicsformativegrade_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ethicsformativegrade',
            old_name='grade',
            new_name='grade_record',
        ),
        migrations.RenameField(
            model_name='ethicssummativegrade',
            old_name='grade',
            new_name='grade_record',
        ),
        migrations.AlterUniqueTogether(
            name='ethicsformativegrade',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ethicssummativegrade',
            unique_together=set(),
        ),
    ]
