# Generated by Django 4.0 on 2022-07-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0051_rename_grade_ethicsformativegrade_grade_record_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ethicsformativegrade',
            unique_together={('ethic', 'grade_record')},
        ),
        migrations.AlterUniqueTogether(
            name='ethicssummativegrade',
            unique_together={('ethic', 'grade_record')},
        ),
    ]
