# Generated by Django 4.0 on 2022-07-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0052_alter_ethicsformativegrade_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethicsgraderecord',
            name='student_discussion_comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
