# Generated by Django 4.0 on 2022-07-28 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0054_rename_grade_grademessages_grade_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GradeMessages',
        ),
    ]
