# Generated by Django 4.0 on 2022-07-28 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0055_delete_grademessages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicatorskillgrade',
            old_name='grade',
            new_name='grade_record',
        ),
        migrations.AlterUniqueTogether(
            name='indicatorskillgrade',
            unique_together={('skill', 'grade_record')},
        ),
    ]
