# Generated by Django 4.0 on 2022-07-29 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_student_active'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('vocational', '0056_rename_grade_indicatorskillgrade_grade_record_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkillGrade',
            new_name='SkillGradeRecord',
        ),
    ]
