# Generated by Django 4.0 on 2022-07-29 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0057_rename_skillgrade_skillgraderecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocational.skillgraderecord')),
                ('score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vocational.skillvalue')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vocational.vocationalskill')),
            ],
            options={
                'unique_together': {('skill', 'grade_record')},
            },
        ),
        migrations.DeleteModel(
            name='IndicatorSkillGrade',
        ),
    ]
