# Generated by Django 4.0 on 2022-10-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0058_skillgrade_delete_indicatorskillgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethicsgraderecord',
            name='student_discussed',
            field=models.DateField(blank=True, null=True, verbose_name='Student Discussed Date'),
        ),
    ]
