# Generated by Django 4.0 on 2022-10-25 01:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0060_ethicsgraderecord_vc_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_ratio', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('summative_ratio', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('track_time', models.BooleanField(default=False)),
                ('time_unit', models.CharField(blank=True, choices=[('h', 'Hours'), ('d', 'Days'), ('w', 'Weeks')], max_length=1, null=True)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocational.schoolyear')),
            ],
        ),
    ]
