# Generated by Django 4.0 on 2022-10-25 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0062_alter_schoolsettings_progress_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethicsgraderecord',
            name='time',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
