# Generated by Django 4.0 on 2022-10-25 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0063_ethicsgraderecord_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='school_year',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vocational.schoolyear'),
        ),
        migrations.DeleteModel(
            name='SchoolOptions',
        ),
    ]
