# Generated by Django 4.0 on 2022-10-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0065_alter_ethicsformativegrade_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethicsgraderecord',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
