# Generated by Django 4.0 on 2022-11-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_student_active'),
        ('vocational', '0066_alter_ethicsgraderecord_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, related_name='student_assignment', to='users.Student'),
        ),
    ]
