# Generated by Django 4.0 on 2022-11-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_student_active'),
        ('vocational', '0067_alter_studentassignment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='student_assignment', to='users.Student'),
        ),
    ]
