# Generated by Django 4.0 on 2022-11-03 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_student_active'),
        ('vocational', '0068_alter_studentassignment_student'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolyear',
            unique_together={('name', 'school')},
        ),
    ]
