# Generated by Django 4.0 on 2022-12-12 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0070_alter_schoolyear_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolSettings',
            new_name='GradeSettings',
        ),
    ]
