# Generated by Django 4.0 on 2022-12-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_school_country'),
        ('vocational', '0072_alter_quarter_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorassignment',
            name='instructor',
            field=models.ManyToManyField(blank=True, related_name='instructor_assignments', to='users.Profile'),
        ),
    ]
