# Generated by Django 4.0 on 2022-12-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0073_alter_instructorassignment_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
