# Generated by Django 4.0 on 2022-12-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0074_schoolyear_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
