# Generated by Django 4.0 on 2022-12-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0075_instructorassignment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
