# Generated by Django 4.0 on 2022-12-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0076_gradesettings_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
