# Generated by Django 4.0 on 2022-12-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0077_department_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
