# Generated by Django 4.0 on 2023-01-13 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_profile_updated_at_student_updated_at'),
        ('vocational', '0078_quarter_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='vocationalskill',
            unique_together={('department', 'name')},
        ),
    ]
