# Generated by Django 4.0 on 2023-06-15 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0079_alter_department_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillgraderecord',
            name='student_discussed',
        ),
        migrations.AddField(
            model_name='skillgraderecord',
            name='evaluation_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
