# Generated by Django 4.0 on 2023-06-19 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0080_remove_skillgraderecord_student_discussed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillvalue',
            old_name='number',
            new_name='score',
        ),
    ]
