# Generated by Django 4.0 on 2023-07-18 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0081_rename_number_skillvalue_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vocationalskill',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='ethicsgraderecord',
            name='suggested_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suggested_level', to='vocational.ethicslevel'),
        ),
    ]
