# Generated by Django 4.0 on 2023-07-19 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0082_alter_vocationalskill_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethicsgraderecord',
            name='accepted_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_level', to='vocational.ethicslevel'),
        ),
    ]
