# Generated by Django 4.0 on 2024-08-19 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0083_ethicsgraderecord_accepted_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField(blank=True, null=True)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('student_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocational.studentassignment')),
            ],
        ),
    ]
