# Generated by Django 4.0 on 2024-08-19 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_school_email_update'),
        ('vocational', '0084_timecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecard',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
