# Generated by Django 5.1 on 2024-08-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0085_timecard_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecard',
            name='timezone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
