# Generated by Django 5.1 on 2024-08-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0086_timecard_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecard',
            name='week_range',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
