# Generated by Django 5.1 on 2024-08-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0088_alter_timecard_week_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocationalskill',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
