# Generated by Django 5.1 on 2024-11-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0089_alter_vocationalskill_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethicsgraderecord',
            name='time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
