# Generated by Django 5.1 on 2025-08-15 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_school_timezone'),
        ('vocational', '0091_alter_vocationalstatus_vocational_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryStudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('student_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocational.studentassignment')),
            ],
        ),
    ]
