# Generated by Django 5.1 on 2025-10-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_school_timezone'),
        ('vocational', '0092_temporarystudentassignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='temporarystudentassignment',
            unique_together={('student_assignment', 'student')},
        ),
    ]
