# Generated by Django 4.0 on 2022-12-13 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_school_email_password'),
        ('emailing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='school_specific_email_message',
            new_name='email_message',
        ),
    ]
