# Generated by Django 4.0 on 2022-12-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0002_rename_school_specific_email_message_email_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='default_email_message',
            name='override_message',
        ),
        migrations.RemoveField(
            model_name='default_email_message',
            name='school',
        ),
    ]
