# Generated by Django 4.0 on 2022-12-16 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_school_email_password'),
        ('emailing', '0003_remove_default_email_message_override_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='override_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_message', models.CharField(max_length=1800)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailing.default_email_message')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
            ],
        ),
    ]
