# Generated by Django 4.0 on 2022-12-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_school_email_password'),
        ('emailing', '0004_override_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='default_email_message',
            new_name='DefaultMessage',
        ),
        migrations.RenameModel(
            old_name='override_messages',
            new_name='OverrideMessage',
        ),
        migrations.RenameModel(
            old_name='email_message',
            new_name='SchoolMessage',
        ),
    ]
