# Generated by Django 4.0 on 2022-12-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0006_rename_default_message_defaultmessage_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultmessage',
            name='subject',
            field=models.CharField(default='subject', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overridemessage',
            name='subject',
            field=models.CharField(default='subject', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolmessage',
            name='subject',
            field=models.CharField(default='subject', max_length=25),
            preserve_default=False,
        ),
    ]
