# Generated by Django 4.0 on 2022-12-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0007_defaultmessage_subject_overridemessage_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultmessage',
            name='subject',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='overridemessage',
            name='subject',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='schoolmessage',
            name='subject',
            field=models.CharField(max_length=225),
        ),
    ]
