# Generated by Django 4.0 on 2023-01-06 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0009_alter_overridemessage_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overridemessage',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overridden', to='emailing.defaultmessage'),
        ),
    ]
