# Generated by Django 4.0 on 2023-02-01 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0011_defaultmessage_updated_at_overridemessage_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefaultMessage',
            new_name='SystemMessages',
        ),
    ]
