# Generated by Django 4.0 on 2023-02-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0012_rename_defaultmessage_systemmessages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SystemMessages',
            new_name='DefaultMessage',
        ),
    ]
