# Generated by Django 4.0 on 2023-02-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0013_rename_systemmessages_defaultmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefaultMessage',
            new_name='SystemMessage',
        ),
    ]
